name: Pacman Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: chethiyab
          outputs: |
            dist/pacman.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist